"""
Django settings for essayCompTutors project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@!cbcu2t_$_%xd9=*&e4^o27-or6aw=*7p81x34s-ve5()ayis'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'essayCompTutors',
    'essaycomp',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'essayCompTutors.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'essayCompTutors.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'essayCompTutors',
        'USER': 'postgres',
        'PASSWORD':'toor',
        'HOST':'localhost',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'essayCompTutors/static')]
STATIC_ROOT=os.path.join(BASE_DIR,'static')

####email settings 
#EMAIL_HOST=os.environ.get('EMAIL_HOST')
#EMAIL_PORT=os.environ.get('EMAIL_PORT')
#EMAIL_HOST_USER=os.environ.get('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD=os.environ.get('EMAIL_HOST_PASSWORD')
#DEFAULT_FROM_EMAIL=os.environ.get('DEFAULT_FROM_EMAIL')
#EMAIL_USE_TSL=os.environ.get('EMAIL_USE_TSL')
#EMAIL_USE_SSL=os.environ.get('EMAIL_USE_SSL')
#email settings 
EMAIL_HOST='mail.essaycomptutors.com'
EMAIL_PORT=465
EMAIL_HOST_USER='info@essaycomptutors.com'
EMAIL_HOST_PASSWORD='essay@2020'
DEFAULT_FROM_RMAIL='info@essaycomptutors.com'
EMAIL_USE_TSL=False
EMAIL_USE_SSL=True

#CHANGE ERROR TO DANGER 
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

AUTH_USER_MODEL = 'authentication.CustomUser' # new